### ISSUE TITLE
FailedJobException: Job failed.  unknown archive format for file

### ISSUE THREAD

**Issue by lorellav** [DHARPA-Project/kiara_plugin.dh_benelux_2023#1]
**Describe the bug**
When running the cell
```
 inputs = {
    "url": "https://github.com/DHARPA-Project/kiara.examples/archive/refs/heads/main.zip",
    "sub_path": "kiara.examples-main/examples/data/language_processing/text_corpus/data"
 }

outputs = kiara.run_job('download.file_bundle', inputs=inputs)
outputs
```
I get the following error message

'FailedJobException: Job failed.

unknown archive format for file `C:\Users\LORELL~1.VIO\AppData\Local\Temp\tmpwi2tmg_0'

I am running the NB in a virtual env with kiara 0.4.35

**Expected behavior**
It should import a bundle of files

**Desktop (please complete the following information):**
 - Windows
 - Chrome
<img width="611" alt="Screenshot 2023-05-18 220318" src="https://github.com/DHARPA-Project/kiara_plugin.dh_benelux_2023/assets/38286337/68c24821-2bb0-4213-a857-16c35bfd5c3f">

**Additional context**
The cell works in colab

**Comment by MariellaCC** [comment]
This error doesn't happen on my side but there were some new releases lately, not sure if that could be related to upgrading.
After doing a git pull if you are working from within the plugin repo, could you please try to pip install the plugin from the terminal in the conda environment like so to see if it helps? :
`pip install git+https://github.com/DHARPA-Project/kiara_plugin.dh_benelux_2023`
and then try to run the notebook again to see if the error is still there.
Thank you

**Comment by makkus** [comment]
Works for me too.

Notebooks are pretty bad for debugging, could you put the code in a python script, something like:

```
from kiara.api import KiaraAPI
import kiara.interfaces.cli

kiara = KiaraAPI.instance()
inputs = {
    "url": "https://github.com/DHARPA-Project/kiara.examples/archive/refs/heads/main.zip",
    "sub_path": "kiara.examples-main/examples/data/language_processing/text_corpus/data"
}

outputs = kiara.run_job('download.file_bundle', inputs=inputs)
print(outputs)
```
And then run it with the DEBUG environment variable set to true. How to set that depends on where you run the script, but with an anaconda terminal this might work:

```
export DEBUG=true 
python <your_script>.py
```
If that doesn't work, on windows doing the following before running the script might or might not be necessary:

```
SET DEBUG=true
SETX DEBUG true
```

**Comment by makkus** [comment]
Ok, it looks like this was fixed with the changes I made to the onboarding module. I'll need to release a new version, but running into problems. Will update here once that's done.

**Comment by makkus** [comment]
Fixed with `kiara_plugin.onboarding==0.4.4`
